// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Home(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsxs("h1", {
                          children: [
                            "Hello ",
                            JsxRuntime.jsx("span", {
                                  children: "ReScript",
                                  className: "font-bold"
                                }),
                            " App"
                          ],
                          className: "text-2xl"
                        }),
                    className: "p-6 rounded-full border-lime-400 border-4 bg-emerald-400"
                  }),
              className: "flex justify-center items-center bg-lime-100 h-dvh"
            });
}

var make = Home;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
